bot_token: 291043729:AAFCb3BkLfTVNMwQypZh6ZIlAmgeHDhb2AE

api_url: https://api.telegram.org/bot

commands:
    test:
        text: TelegramBot is working!
        description: Команда для тестирования сервиса
        type: Text
    user:
        description: Команда получения информации о пользователе.
        template: /user номер_договора
        example: /user 70001
        number_parameters: 1
        url: http://localhost/api2/web/account
        ping: http://localhost/api2/web/status
        type: URL
        commands:
            create:
                url:
                fields:
    404:
        text: Команда не найдена!

agreements:
    new_number:
        - {key: 2, description: "Новая Чара, Удокан", query: 'select number + 1 from `agreements` WHERE LEFT(number,1)=2 AND state=0 AND number < 28888 ORDER BY number DESC LIMIT 1'}
        - {key: 7, description: "Куанда", query: 'select number + 1 from `agreements` WHERE LEFT(number,1)=7 AND state=0 ORDER BY number DESC LIMIT 1'}

security:
    administrators:
        '427997461': 'Техподдержка'
        '238433653': 'Александр Бурко'
        '322978806': 'Иван'
        '255239781': 'Анна Вейс'
        '247600037': 'Владислав Иванов'
        '272313777': 'VitalyV'
        '290937691': 'Khaustov'


